DROP TABLE STUDENT;

DROP TABLE STUDENT_LOGIN;
	
CREATE TABLE STUDENT 
   (STUDENT_ID INT NOT NULL AUTO_INCREMENT, 
	FIRSTNAME VARCHAR(30) NOT NULL , 
	LASTNAME VARCHAR(30) NOT NULL ,
	DOB DATE NOT NULL , 
	GPA FLOAT NOT NULL,
	REG_COURSE_ID INT NOT NULL,
	STREET VARCHAR(140) NOT NULL , 
	CITY VARCHAR(20) NOT NULL,
	STATE VARCHAR(20) NOT NULL,
	ZIPCODE VARCHAR(10) NOT NULL,	
	PRIMARY KEY (STUDENT_ID)
	)AUTO_INCREMENT=1000;
	
CREATE TABLE STUDENT_LOGIN 
   (STUDENT_ID INT NOT NULL, 
	USERNAME VARCHAR(40) NOT NULL , 
	PASSWORD VARCHAR(20) NOT NULL ,
	CREATED_BY VARCHAR(20) NOT NULL , 
	CREATED_DATE DATE NOT NULL , 
	PRIMARY KEY (USERNAME),
	FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
	);




select * from student_login;

select * from student;

insert into student values(1001,"Kavitha","Srinivasan",'1983-11-15',9.9,123,"street","city","state","zipcode");
insert into student_login values(1001,"kavitha","kavitha","manual",'2015-05-22');
	 
delete from student_login;
	 
commit;